version: '3.1'
services:
  db:
    image: postgres:latest
    ports:
    - '65432:5432'
    environment:
      POSTGRES_USER: 'wunderpong'
      POSTGRES_PASSWORD: 'wunderpong'
      POSTGRES_DB: 'wunderpong_test'
